<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Robson Bruno Dutra Perreira">

<title>3&nbsp; Regressão linear simples, múltipla e polinomial – Aprendizado Supervisionado, uma abordagem com implementações em R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./AS_vicio_var.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./AS_reg_ols.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regressão linear simples, múltipla e polinomial</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Aprendizado Supervisionado, uma abordagem com implementações em R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./AS_Intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introdução ao aprendizado supervisionado</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./AS_vicio_var.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Conflito entre vício e variância no Aprendizado supervisionado</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./AS_reg_ols.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regressão linear simples, múltipla e polinomial</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#regressão-linear-simples-múltipla-e-polinomial" id="toc-regressão-linear-simples-múltipla-e-polinomial" class="nav-link active" data-scroll-target="#regressão-linear-simples-múltipla-e-polinomial"><span class="header-section-number">3.1</span> Regressão linear simples, múltipla e polinomial</a>
  <ul class="collapse">
  <li><a href="#regressão-linear-simples" id="toc-regressão-linear-simples" class="nav-link" data-scroll-target="#regressão-linear-simples"><span class="header-section-number">3.1.1</span> Regressão linear simples</a></li>
  <li><a href="#regressão-linear-múltipla" id="toc-regressão-linear-múltipla" class="nav-link" data-scroll-target="#regressão-linear-múltipla"><span class="header-section-number">3.1.2</span> Regressão linear múltipla</a></li>
  <li><a href="#codificação-de-variáveis-categóricas-em-regressão-múltipla" id="toc-codificação-de-variáveis-categóricas-em-regressão-múltipla" class="nav-link" data-scroll-target="#codificação-de-variáveis-categóricas-em-regressão-múltipla"><span class="header-section-number">3.1.3</span> Codificação de variáveis categóricas em regressão múltipla</a></li>
  <li><a href="#regressão-polinomial" id="toc-regressão-polinomial" class="nav-link" data-scroll-target="#regressão-polinomial"><span class="header-section-number">3.1.4</span> Regressão polinomial</a></li>
  </ul></li>
  <li><a href="#implementações-em-r" id="toc-implementações-em-r" class="nav-link" data-scroll-target="#implementações-em-r"><span class="header-section-number">3.2</span> Implementações em R</a>
  <ul class="collapse">
  <li><a href="#caso-1---regressão-linear-simples" id="toc-caso-1---regressão-linear-simples" class="nav-link" data-scroll-target="#caso-1---regressão-linear-simples"><span class="header-section-number">3.2.1</span> Caso 1 - regressão linear simples</a></li>
  <li><a href="#regressão-linear-múltipla-1" id="toc-regressão-linear-múltipla-1" class="nav-link" data-scroll-target="#regressão-linear-múltipla-1"><span class="header-section-number">3.2.2</span> Regressão linear múltipla</a></li>
  <li><a href="#regressão-múltipla-com-variáveis-categóricas" id="toc-regressão-múltipla-com-variáveis-categóricas" class="nav-link" data-scroll-target="#regressão-múltipla-com-variáveis-categóricas"><span class="header-section-number">3.2.3</span> Regressão múltipla com variáveis categóricas</a></li>
  <li><a href="#regressão-polinomial-1" id="toc-regressão-polinomial-1" class="nav-link" data-scroll-target="#regressão-polinomial-1"><span class="header-section-number">3.2.4</span> Regressão polinomial</a></li>
  </ul></li>
  <li><a href="#referências" id="toc-referências" class="nav-link" data-scroll-target="#referências">Referências</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regressão linear simples, múltipla e polinomial</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Robson Bruno Dutra Perreira </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="regressão-linear-simples-múltipla-e-polinomial" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="regressão-linear-simples-múltipla-e-polinomial"><span class="header-section-number">3.1</span> Regressão linear simples, múltipla e polinomial</h2>
<section id="regressão-linear-simples" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="regressão-linear-simples"><span class="header-section-number">3.1.1</span> Regressão linear simples</h3>
<p>Seja um problema onde deseja-se prever uma resposta contínua, <span class="math inline">\(y \in \mathbb{R}\)</span>, em função de uma única variável independente também contínua, <span class="math inline">\(x \in \mathbb{R}\)</span>. Conforme observado graficamente na <a href="#fig-data" class="quarto-xref">Figura&nbsp;<span>3.1</span></a>, pode-se considerar em diversos casos a aproximação de uma função linear para tal relação.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-data" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="AS_reg_ols_files/figure-html/fig-data-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.1: Exemplo de conjunto de dados para regressão linear simples
</figcaption>
</figure>
</div>
</div>
</div>
<p>Tal aproximação pode ser descrita pela Equação à seguir, onde <span class="math inline">\(\hat{y}\)</span> consiste no valor predito de <span class="math inline">\(y\)</span>, <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span> são coeficientes chamados de intercepto ou constante e coeficiente linear ou inclinação, respectivamente. Enquanto <span class="math inline">\(\beta_0\)</span> mede o valor da resposta prevista para <span class="math inline">\(x=0\)</span>, <span class="math inline">\(\beta_1\)</span> consiste na mudança média da resposta para o incremento de uma unidade de <span class="math inline">\(x\)</span>.</p>
<p><span class="math display">\[
\hat{y} = \beta_0 + \beta_1x
\]</span></p>
<p>A <a href="#fig-lm" class="quarto-xref">Figura&nbsp;<span>3.2</span></a> plota para os dados plotados anteriormente a linha azul do modelo de regressão linear simples obtido.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-lm" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="AS_reg_ols_files/figure-html/fig-lm-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.2: Modelo de regressão linear simples
</figcaption>
</figure>
</div>
</div>
</div>
<p>Para este caso inicial os coeficientes de regressão estimados são:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)           x 
  10.927762    2.728817 </code></pre>
</div>
</div>
<p>A primeira pergunta a ser feita seria como estimar tais coeficientes de regressão. Pode-se pensar em estimativas que minimizem o erro de previsão. Conforme, plotado na <a href="#fig-erros" class="quarto-xref">Figura&nbsp;<span>3.3</span></a> em linhas verticais vermelhas, o erro de previsão seria a diferença entre o valor experimental e o previsto, <span class="math inline">\(\varepsilon_i = y_i - \hat{y}_i\)</span>, <span class="math inline">\(i = 1, ...., N\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-erros" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-erros-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="AS_reg_ols_files/figure-html/fig-erros-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-erros-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.3: Erros do modelo de regressão linear simples
</figcaption>
</figure>
</div>
</div>
</div>
<p>Neste sentido, as observações da variável dependente ou resposta podem ser descritas conforme segue.</p>
<p><span class="math display">\[
\begin{aligned}
y_i = \hat{y}_i + \varepsilon_i \\
y_i = \beta_0 + \beta_1x_i + \varepsilon_i \\
\end{aligned}
\]</span></p>
<p>Tomando <span class="math inline">\(N\)</span> observações retiradas da população de interesse, <span class="math inline">\((x_1, y_1), (x_2, y_2), ..., (x_N, y_N)\)</span>, pode-se pensar em um modelo que minimize os erros de previsão para a amostra disponível. Uma vez que o erro é normalmente distribuído, com média nula e variância <span class="math inline">\(\sigma_\varepsilon^2\)</span>, sendo os resíduos normalmente distribuídos, com média nula e variância igual a <span class="math inline">\(\sigma_\varepsilon^2\)</span>, <span class="math inline">\(\varepsilon \sim N(0,\sigma_\varepsilon^2)\)</span>, pode-se trabalhar a minimização da soma dos quadrados dos erros de previsão, <span class="math inline">\(\sum_{i=1}^{N}\varepsilon_i^2\)</span>.</p>
<p>A <a href="#tbl-dados" class="quarto-xref">Tabela&nbsp;<span>3.1</span></a> expõe algumas das observações para os dados plotados anteriormente, bem como os valores preditos e erros associados.</p>
<div class="cell">
<div id="tbl-dados" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dados-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;3.1: Dados para regressão linear simples e previsões
</figcaption>
<div aria-describedby="tbl-dados-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">x</th>
<th style="text-align: right;">y</th>
<th style="text-align: right;">y_hat</th>
<th style="text-align: right;">erro</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1.093333</td>
<td style="text-align: right;">9.389117</td>
<td style="text-align: right;">13.91127</td>
<td style="text-align: right;">-4.5221504</td>
</tr>
<tr class="even">
<td style="text-align: right;">4.106335</td>
<td style="text-align: right;">29.785746</td>
<td style="text-align: right;">22.13320</td>
<td style="text-align: right;">7.6525477</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9.138367</td>
<td style="text-align: right;">29.774229</td>
<td style="text-align: right;">35.86469</td>
<td style="text-align: right;">-6.0904613</td>
</tr>
<tr class="even">
<td style="text-align: right;">24.613730</td>
<td style="text-align: right;">78.467084</td>
<td style="text-align: right;">78.09412</td>
<td style="text-align: right;">0.3729679</td>
</tr>
<tr class="odd">
<td style="text-align: right;">38.963445</td>
<td style="text-align: right;">126.273606</td>
<td style="text-align: right;">117.25185</td>
<td style="text-align: right;">9.0217521</td>
</tr>
<tr class="even">
<td style="text-align: right;">56.628047</td>
<td style="text-align: right;">155.103936</td>
<td style="text-align: right;">165.45531</td>
<td style="text-align: right;">-10.3513755</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>A sintaxe anteriormente apresentada pode ser escrita de forma matricial, conforme segue, onde <span class="math inline">\(\mathbf{x}_{[2 \times N]}\)</span> consiste em uma matriz relacionada às observações independentes, com uma coluna de valores unitários associada à <span class="math inline">\(\beta_0\)</span> e outra com as observações de <span class="math inline">\(x\)</span>, portanto associada a <span class="math inline">\(\beta_1\)</span>. <span class="math inline">\(\mathbf{y}_{[N\times1]}\)</span> consiste no vetor de observações da resposta, <span class="math inline">\(\mathbf{\varepsilon}_{[N\times1]}\)</span> consiste no vetor de erros ou resíduos de previsão e <span class="math inline">\(\mathbf{\beta}_{[2\times1]}\)</span> consiste em um vetor de coeficientes.</p>
<p><span class="math display">\[
\begin{aligned}
\mathbf{y} = \mathbf{X}\mathbf{\beta} + \mathbf{\varepsilon}
\end{aligned}
\]</span></p>
<p>Tais elementos matriciais podem ser escritos de forma genérica conforme segue.</p>
<p><span class="math display">\[
\mathbf{X} =
\begin{bmatrix}
1 &amp; x_{1}\\
1 &amp; x_{2}\\
\vdots &amp; \vdots \\
1 &amp; x_{N}\\
\end{bmatrix} =
\begin{bmatrix}
1 &amp; 1.093\\
1 &amp; 4.106\\
\vdots &amp; \vdots \\
1 &amp; 96.206\\
\end{bmatrix}
\]</span></p>
<p><span class="math display">\[
\mathbf{y} =
\begin{bmatrix}
y_{1}\\
y_{2}\\
\vdots \\
y_{N}\\
\end{bmatrix} =
\begin{bmatrix}
9.389\\
29.786\\
\vdots \\
290.028\\
\end{bmatrix}
\]</span></p>
<p><span class="math display">\[
\mathbf{\varepsilon} =
\begin{bmatrix}
\varepsilon_{1}\\
\varepsilon_{2}\\
\vdots \\
\varepsilon_{N}\\
\end{bmatrix} =
\begin{bmatrix}
-4.522\\
7.653\\
\vdots \\
16.571\\
\end{bmatrix}\text{,    e} \\
\]</span></p>
<p><span class="math display">\[
\mathbf{\beta}^T =
\begin{bmatrix}
\beta_0 &amp; \beta_1\\
\end{bmatrix} =
\begin{bmatrix}
10.928  &amp; 2.729 \\
\end{bmatrix}
\]</span></p>
<p>Tomando tal notação, a soma dos quadrados dos erros pode ser descrita como <span class="math inline">\(\sum_{i=1}^{N}\varepsilon_i^2 = \mathbf{\varepsilon}^T\mathbf{\varepsilon}\)</span>. Desenvolvendo tal expressão tem-se:</p>
<p><span class="math display">\[
\begin{aligned}
L(\mathbf{\beta}) = \mathbf{\varepsilon}^T\mathbf{\varepsilon} = (\mathbf{y} - \mathbf{X}\mathbf{\beta})^T(\mathbf{y} - \mathbf{X}\mathbf{\beta}) \\
\mathbf{y}^T\mathbf{y} - 2\mathbf{\beta}^T\mathbf{X}^T\mathbf{y} + \mathbf{\beta}^T\mathbf{X}^T\mathbf{X}\mathbf{\beta}
\end{aligned}
\]</span></p>
<p>Para minimizar <span class="math inline">\(L\)</span> em relação à estimativa de <span class="math inline">\(\mathbf{\beta}\)</span>, pode-se diferenciar tal quantidade em relação à <span class="math inline">\(\mathbf{\beta}\)</span> e igualar a zero:</p>
<p><span class="math display">\[
\begin{aligned}
\frac{\partial L}{\partial \mathbf{\beta}} = -2\mathbf{X}^T\mathbf{y} + 2\mathbf{X}^T\mathbf{X}\mathbf{\beta} = 0 \\
\hat{\mathbf{\beta}} = (\mathbf{X}^T\mathbf{X})^{-1}(\mathbf{X}^T\mathbf{y})
\end{aligned}
\]</span></p>
<p>Tal solução constitui as chamadas equações normais de mínimos quadrados.</p>
<p>Ao obter um modelo de regressão é sempre importante observar os resíduos, os quais devem ser normalmente distribuídos, independentes e homocedásticos. Tais pressuposições implicam que o modelo obtido por mínimos quadrados é paramétrico, uma vez que pressupõe-se uma distribuição para os resíduos. Neste curso de aprendizado não supervisionado, serão estudados diversos modelos que não implicam qualquer distribuição acerca dos resíduos ou dados sendo, portanto, livres de distribuição e ditos não-paramétricos. A <a href="#fig-resi" class="quarto-xref">Figura&nbsp;<span>3.4</span></a> expõe alguns gráficos dos resíduos os erros do modelo obtido, os quais podem servir para avaliação da normalidade do modelo, bem como para identificação de observações não usuais.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-resi" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-resi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="AS_reg_ols_files/figure-html/fig-resi-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-resi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.4: Resíduos do modelo de regressão linear simples
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="regressão-linear-múltipla" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="regressão-linear-múltipla"><span class="header-section-number">3.1.2</span> Regressão linear múltipla</h3>
<p>No caso de onde há múltiplas variáveis independentes ou regressoras de interesse, <span class="math inline">\(x_1, x_2, ..., x_k\)</span> pode-se considerar o modelo com um coeficiente linear associado a cada variável, isto é:</p>
<p><span class="math display">\[
\hat{y}_i = \beta_0 + \beta_1x_{i1} + \beta_2x_{i2} + \cdots + \beta_kx_{ik} = \beta_0 + \sum_{j=1}^{k}\beta_jx_{ij},  
\]</span></p>
<p>ou de forma matricial com <span class="math inline">\(\mathbf{X}_{[N\times (k+1)]}\)</span> e <span class="math inline">\(\mathbf{\beta}_{[(k+1) \times 1]}\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
\hat{\mathbf{y}} = \mathbf{X}\mathbf{\beta}
\end{aligned},
\]</span> com:</p>
<p><span class="math display">\[
\mathbf{X} =
\begin{bmatrix}
1 &amp; x_{11} &amp; x_{12} &amp; \cdots &amp; x_{1k}\\
1 &amp; x_{21} &amp; x_{22} &amp; \cdots &amp; x_{2k} \\
\vdots &amp; \vdots &amp; \vdots &amp; \ddots &amp; \vdots\\
1 &amp; x_{N1} &amp; x_{N2} &amp; \cdots &amp; x_{Nk} \\
\end{bmatrix}, e\\
\]</span></p>
<p><span class="math display">\[
\mathbf{\beta}^T =
\begin{bmatrix}
\beta_0 &amp; \beta_1 &amp; \cdots &amp; \beta_k\\
\end{bmatrix}. \\
\]</span></p>
<p>As estimativas de mínimos quadrados, deduzidas para o caso simples, <span class="math inline">\(\hat{\mathbf{\beta}} = (\mathbf{X}^T\mathbf{X})^{-1}(\mathbf{X}^T\mathbf{y})\)</span>, também atendem ao caso múltiplo. Uma forma de medir o ajuste do modelo obtido aos dados seria a partir do cálculo do coeficiente de determinação múltipla, <span class="math inline">\(R^2\)</span>, conforme segue,</p>
<p><span class="math display">\[
\begin{align}
R^2 = 1- SS_{E}/SS_T \\
R^2 = 1- \frac{\sum_{i=1}^{N}(y_i-\hat{y}_i)^2}{\sum_{i=1}^{N}(y_i-\overline{y}_i)^2},
\end{align}
\]</span></p>
<p>ou utilizando outras métricas de ajuste. É interessante que tais métricas sejam também calculadas para dados futuros ou de teste, de forma a evitar sobreajuste do modelo. Uma observação importante é relacionada à utilização da Análise de variância (ANOVA) para obtenção de tais métricas. Além do <span class="math inline">\(R^2\)</span>, ao se utilizar a ANOVA, há a possibilidade de calcular o coeficiente de determinação ajustado, <span class="math inline">\(R^2_{adj}\)</span>, isto é:</p>
<p><span class="math display">\[
R^2_{adj} = 1 - \frac{SS_{E}/(N-k)}{SS_T/(N-1)}
\]</span></p>
<p>Esta métrica é mais honesta uma vez que penaliza o modelo pela adição de mais coeficientes. O <span class="math inline">\(R^2\)</span> sempre aumentará com adição de novos coeficientes, enquanto o <span class="math inline">\(R^2_{adj}\)</span> será mais baixo casos novos termos adicionados não apresentem significância estatística. Entretanto, quando outros métodos de aprendizado não paramétricos são utilizados, especialmente os que não tem origem na estatística mas na computação, tal métrica não pode ser calculada. No contexto de aprendizado supervisionado é mais interessante realizar a validação cruzada e estimar o desempenho do modelo em dados futuros, viabilizando a comparação de tipos distintos de modelos.</p>
<p>O teste t para os coeficientes de regressão pode ser calculado para medir a significância de cada coeficiente e testar as seguintes hipóteses para cada coeficiente de regressão.</p>
<p><span class="math display">\[
\begin{matrix}
H_0: \beta_j = 0 \\
H_1: \beta_j \neq 0, j = 1, ..., k\\
\end{matrix}
\]</span></p>
<p>O teste é calculado conforme segue, onde <span class="math inline">\(C_j\)</span> é o valor da <span class="math inline">\(j\)</span>-ésima linha e <span class="math inline">\(j\)</span>-ésima coluna da matriz <span class="math inline">\((\mathbf{X}^T\mathbf{X})^{-1}\)</span>, correspondente a <span class="math inline">\(\beta_j\)</span>. A hipótese nula é rejeitada se <span class="math inline">\(t_{0j} &gt; t_{[\alpha/2,N-k]}\)</span>, onde <span class="math inline">\(\alpha\)</span> é o nível de significância de interesse.</p>
<p><span class="math display">\[
t_{0j} = \frac{\hat{\beta}_j}{\sqrt{C_jSS_E/(N-k)}}
\]</span></p>
<p>Analogamente, estimativas intervalares para os coeficientes podem ser obtidas como segue, as quais consistem em intervalos que garantem <span class="math inline">\(\gamma = 1-\alpha\)</span> de confiança de encontrar os verdadeiros valores dos coeficientes de regressão.</p>
<p><span class="math display">\[
\hat{\beta}_j \pm t_{[\alpha/2,N-k]}\sqrt{C_jSS_E/(N-k)}
\]</span></p>
<p>A <a href="#fig-mulreg" class="quarto-xref">Figura&nbsp;<span>3.5</span></a> ilustra graficamente um modelo de regressão linear múltipla para prever o preço de carros usados em função da idade e quilometragem.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mulreg" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mulreg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="AS_reg_ols_files/figure-html/fig-mulreg-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mulreg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.5: Modelo de regressão linear múltipla para prever o preço de carros usados em função da quilometragem e idade
</figcaption>
</figure>
</div>
</div>
</div>
<p>Para este caso, os coeficientes estimados são apresentados a seguir. Estes foram estimados nas unidades originais das variáveis. Porém, para fins de inferência, é importante padronizar as variáveis regressoras.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)     Mileage         Age 
21.54307990 -0.05314626 -0.84234949 </code></pre>
</div>
</div>
<p>O modelo pode ser escrito conforme segue.</p>
<p><span class="math display">\[
\hat{y} = 21,543 - 0,0531x_1 - 0,842x_2
\]</span></p>
<p>O teste t para os coeficientes de regressão resultante é apresentado a seguir. As duas variáveis regressoras foram antes padronizadas para evitar efeito de escala e unidade de medida. Como <span class="math inline">\(|t_{\alpha/2,N-k}|\)</span> = 1.987, tem-se que todos os coeficientes são significativos, uma vez que <span class="math inline">\(t_{0j} &gt; t_{\alpha/2,N-k}\)</span>, <span class="math inline">\(\forall j = 1, ..., k\)</span>. Pode-se também considerar o <span class="math inline">\(p-value\)</span> que é a probabilidade de erro na rejeição da hipótese nula, <span class="math inline">\(H_0\)</span>, associada ao valor calculado <span class="math inline">\(t_0\)</span>. Se <span class="math inline">\(p-value &lt; \alpha\)</span>, rejeita-se <span class="math inline">\(H_0\)</span>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Mileage + Age, data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.5429 -1.2795 -0.2982  1.5275  7.1967 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  13.7478     0.2483  55.364  &lt; 2e-16 ***
Mileage      -1.9401     0.4406  -4.404 3.02e-05 ***
Age          -3.3175     0.4406  -7.530 4.42e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.356 on 87 degrees of freedom
Multiple R-squared:  0.8239,    Adjusted R-squared:  0.8198 
F-statistic: 203.5 on 2 and 87 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>A <a href="#tbl-ic" class="quarto-xref">Tabela&nbsp;<span>3.2</span></a> apresentam os intervalos de confiança de 0,95 para os coeficientes codificados.</p>
<div class="cell">
<div id="tbl-ic" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;3.2: Intervalos de confiança para os coeficientes de regressão múltipla
</figcaption>
<div aria-describedby="tbl-ic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">X2.5..</th>
<th style="text-align: right;">X97.5..</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">13.254224</td>
<td style="text-align: right;">14.241331</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mileage</td>
<td style="text-align: right;">-2.815845</td>
<td style="text-align: right;">-1.064452</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">-4.193231</td>
<td style="text-align: right;">-2.441839</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Além de considerar termos de múltiplas variáveis, é possível considerar a interação entre estas, colocando na matriz <span class="math inline">\(\mathbf{X}\)</span> colunas com multiplicação ou produto das variáveis de interesse e no modelo termos da forma <span class="math inline">\(\beta_{ij}x_ix_j\)</span>. Para o caso em estudo um modelo de regressão múltipla com interação ficaria conforme segue.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Mileage * Age, data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.1277 -1.4495 -0.2671  1.7765  6.1130 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  13.0272     0.3381  38.532  &lt; 2e-16 ***
Mileage      -2.0909     0.4247  -4.924 4.06e-06 ***
Age          -3.7683     0.4477  -8.417 7.55e-13 ***
Mileage:Age   0.8844     0.2952   2.997  0.00357 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.255 on 86 degrees of freedom
Multiple R-squared:  0.8405,    Adjusted R-squared:  0.835 
F-statistic: 151.1 on 3 and 86 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>É importante esclarecer que no caso de modelos de regressão múltipla com termos de interação, a matriz <span class="math inline">\(\mathbf{X}\)</span> apresentará mais que <span class="math inline">\(k+1\)</span> colunas, sendo adicionadas as colunas das respectivas interações, como sendo o produto das colunas das variáveis envolvidas em cada termo adicionado.</p>
</section>
<section id="codificação-de-variáveis-categóricas-em-regressão-múltipla" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="codificação-de-variáveis-categóricas-em-regressão-múltipla"><span class="header-section-number">3.1.3</span> Codificação de variáveis categóricas em regressão múltipla</h3>
<p>Retomando o problema de regressão do preço de revenda de carros considerando o ano e a quilometragem, imagine uma terceira variável regressora que determina o modelo ou tipo do veículo. Tal variável apresenta três categorias, <em>Mazda6</em>, <em>Accord</em> e <em>Maxima</em>. A <a href="#tbl-carrr" class="quarto-xref">Tabela&nbsp;<span>3.3</span></a> expõe algumas observações do conjuunto de dados.</p>
<div class="cell">
<div id="tbl-carrr" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-carrr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;3.3: Dados de preços de carros usados
</figcaption>
<div aria-describedby="tbl-carrr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">CarType</th>
<th style="text-align: right;">Age</th>
<th style="text-align: right;">Mileage</th>
<th style="text-align: right;">Price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Mazda6</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">17.8</td>
<td style="text-align: right;">15.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Mazda6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">19.0</td>
<td style="text-align: right;">16.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">50</td>
<td style="text-align: left;">Accord</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">150.5</td>
<td style="text-align: right;">7.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">51</td>
<td style="text-align: left;">Accord</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">65.2</td>
<td style="text-align: right;">11.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">70</td>
<td style="text-align: left;">Maxima</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">38.6</td>
<td style="text-align: right;">20.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">71</td>
<td style="text-align: left;">Maxima</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">42.1</td>
<td style="text-align: right;">20.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Para trabalhar com a variável modelo e qualquer outra variável qualitativa ou categórica em regressão múltipla, pode-se utilizar de variáveis <em>dummy</em> também conhecidas como dicotômicas ou binárias. No caso de três categorias, como no exemplo acima, duas variáveis <em>dummy</em> seriam suficientes. Ao criar uma coluna denominada <code>Mazda6</code>, com 1, se <code>Mazda6</code> e 0, caso contrário e, de forma análoga, uma coluna para <code>Accord</code>, caso uma determinada observação receba 0 em ambas colunas, o modelo do carro seria o <code>Maxima</code>.</p>
<p>Seja <span class="math inline">\(x_1\)</span> o ano, <span class="math inline">\(x_2\)</span> a quiometragem,</p>
<p><span class="math display">\[
x_3 = \bigg\{
\begin{matrix}
1, \text{ se Mazda6} \\
0, \text{ cc}\\
\end{matrix}
\]</span> e</p>
<p><span class="math display">\[
x_4 = \bigg\{
\begin{matrix}
1, \text{ se Accord} \\
0, \text{ cc}\\
\end{matrix}
\]</span></p>
<p>O modelo de regressão pode ser escrito conforme segue.</p>
<p><span class="math display">\[
\hat{y}_i = \beta_0 + \beta_1x_{i1} + \beta_2x_{i2} + \beta_3x_{i3} + \beta_4x_{i4}
\]</span></p>
<p>Fica claro que, neste tipo de modelo, o coeficiente <span class="math inline">\(\beta_3\)</span> é uma constante adicionada a <span class="math inline">\(\beta_0\)</span> caso o modelo do carro seja <code>Mazda6</code>. Uma explicação análoga pode ser feita para <span class="math inline">\(\beta_4\)</span>. Portanto, tais termos não mudam a inclinação do modelo, apenas o intercepto. É possível adicionar termos de interação entre variáveis dicotômicas e variáveis contínuas, o que na prática serviria para mudar a inclinação ou coeficientes das variáveis contínuas. Retomando a criação de variáveis dicotômicas para o exemplo em questão, tem-se as colunas com tais variáveis criadas na <a href="#tbl-carsint" class="quarto-xref">Tabela&nbsp;<span>3.4</span></a>.</p>
<div class="cell">
<div id="tbl-carsint" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-carsint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;3.4: Dados de carros usados com colunas das variáveis dicotômicas
</figcaption>
<div aria-describedby="tbl-carsint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">CarType</th>
<th style="text-align: right;">Age</th>
<th style="text-align: right;">Price</th>
<th style="text-align: right;">Mileage</th>
<th style="text-align: right;">Mazda6</th>
<th style="text-align: right;">Accord</th>
<th style="text-align: right;">Maxima</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Mazda6</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">15.9</td>
<td style="text-align: right;">17.8</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Mazda6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">16.4</td>
<td style="text-align: right;">19.0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">50</td>
<td style="text-align: left;">Accord</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">7.9</td>
<td style="text-align: right;">150.5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">51</td>
<td style="text-align: left;">Accord</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">11.7</td>
<td style="text-align: right;">65.2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">70</td>
<td style="text-align: left;">Maxima</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">20.0</td>
<td style="text-align: right;">38.6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">71</td>
<td style="text-align: left;">Maxima</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">20.0</td>
<td style="text-align: right;">42.1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>O modelo com estas variáveis e as duas consideradas anteriormente ficaria conforme exposto a seguir.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Mileage + Age + Mazda6 + Accord, data = data)

Residuals:
   Min     1Q Median     3Q    Max 
-4.588 -1.632 -0.178  1.196  6.861 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  14.5616     0.4082  35.672  &lt; 2e-16 ***
Mileage      -1.8975     0.4226  -4.490 2.23e-05 ***
Age          -3.2185     0.4253  -7.567 4.17e-11 ***
Mazda6       -2.1158     0.5750  -3.680 0.000409 ***
Accord       -0.3257     0.5873  -0.555 0.580651    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.187 on 85 degrees of freedom
Multiple R-squared:  0.8517,    Adjusted R-squared:  0.8447 
F-statistic:   122 on 4 and 85 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="regressão-polinomial" class="level3" data-number="3.1.4">
<h3 data-number="3.1.4" class="anchored" data-anchor-id="regressão-polinomial"><span class="header-section-number">3.1.4</span> Regressão polinomial</h3>
<p>É possível em regressão simples ou múltipla realizar transformações nos preditores de forma a incluir termos polinomiais associados à uma ou mais variáveis independentes. Para o caso simples, um modelo de regressão polinomial pode ser escrito conforme segue, onde <span class="math inline">\(p\)</span> é a ordem do modelo de regressão polinomial.</p>
<p><span class="math display">\[
\hat{y} = \beta_0 + \beta_1x + \beta_2x^2 + \beta_3x^3 + ... \beta_px^p
\]</span></p>
<p>Considerando a notação matricial, a matriz <span class="math inline">\(\mathbf{X}\)</span> fica conforme segue, podendo-se utilizar novamente as equações normais de mínimos quadrados para estimar os coeficientes, <span class="math inline">\(\hat{\mathbf{\beta}} = (\mathbf{X}^T\mathbf{X})^{-1}(\mathbf{X}^T\mathbf{y})\)</span>.</p>
<p><span class="math display">\[
\mathbf{X} =
\begin{bmatrix}
1 &amp; x_{11} &amp; x_{11}^2 &amp; \cdots &amp; x_{p1}^p\\
1 &amp; x_{12} &amp; x_{12}^2 &amp; \cdots &amp; x_{p2}^p \\
\vdots &amp; \vdots &amp; \vdots &amp; \ddots &amp; \vdots\\
1 &amp; x_{1N} &amp; x_{1N}^2 &amp; \cdots &amp; x_{pN}^p \\
\end{bmatrix}\\
\]</span></p>
<p>Sejam os dados da massa de um paciente em kg medidos ao longo de 8 meses de um programa de perda de peso, conforme <a href="#fig-rehab" class="quarto-xref">Figura&nbsp;<span>3.6</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-rehab" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rehab-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="AS_reg_ols_files/figure-html/fig-rehab-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rehab-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.6: Dados de perda de peso em função do tempo no programa
</figcaption>
</figure>
</div>
</div>
</div>
<p>Considerando um modelo linear para tais dados, os resíduos obtidos são plotados na <a href="#fig-rehabresi" class="quarto-xref">Figura&nbsp;<span>3.7</span></a>. Pode-se observar claramente um padrão de não linearidade nos resíduos em relação aos valores ajustados, indicando o ajuste de um modelo não linear.</p>
<div class="cell" data-fig-caption="Resíduos para um modelo linear ajustado aos dados de perda de peso">
<div class="cell-output-display">
<div id="fig-rehabresi" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rehabresi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="AS_reg_ols_files/figure-html/fig-rehabresi-1.png" id="fig-rehabresi" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-rehabresi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.7
</figcaption>
</figure>
</div>
</div>
</div>
<p>Pode-se pensar, portanto, em um modelo de regressão quadrático para aproximar o peso em função de dias. A curva plotada na <a href="#fig-rehab" class="quarto-xref">Figura&nbsp;<span>3.6</span></a> consiste em tal modelo.</p>
<div class="cell" data-fig-caption="Modelo de regressão quadrático para os dados de perda de peso">
<div class="cell-output-display">
<div id="fig-rehablm" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rehablm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="AS_reg_ols_files/figure-html/fig-rehablm-1.png" id="fig-rehablm" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-rehablm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.8
</figcaption>
</figure>
</div>
</div>
</div>
<p>O modelo quadrático obtido e associado ao gráfico anterior é exposto a seguir.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Weight ~ Days + I(Days^2), data = rehab)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.9034 -0.5842 -0.1188  0.4774  2.6315 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.833e+02  3.521e-01  520.72   &lt;2e-16 ***
Days        -4.565e-01  6.520e-03  -70.03   &lt;2e-16 ***
I(Days^2)    6.930e-04  2.614e-05   26.51   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9386 on 49 degrees of freedom
Multiple R-squared:  0.9981,    Adjusted R-squared:  0.998 
F-statistic: 1.287e+04 on 2 and 49 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Os resíduos para o modelo quadrático são plotados na <a href="#fig-rehabresi" class="quarto-xref">Figura&nbsp;<span>3.7</span></a>.</p>
<div class="cell" data-fig-caption="Resíduos para o modelo quadrático ajustado aos dados de perda de peso">
<div class="cell-output-display">
<div id="fig-rehabresi2" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rehabresi2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="AS_reg_ols_files/figure-html/fig-rehabresi2-1.png" id="fig-rehabresi2" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-rehabresi2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.9
</figcaption>
</figure>
</div>
</div>
</div>
<p>Finalmente, tal modelo pode ser escrito conforme segue.</p>
<p><span class="math display">\[
\hat{y} = 183,3 -0,456x + 6,930\times10^{-4}x^2
\]</span></p>
</section>
</section>
<section id="implementações-em-r" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="implementações-em-r"><span class="header-section-number">3.2</span> Implementações em R</h2>
<p>A seguir será expostos as implementações necessárias para obter os resultados do capítulo. Alguns exemplos aqui expostos são distintos dos do capítulo, sendo os resultados das implementações apresentados integralmente.</p>
<section id="caso-1---regressão-linear-simples" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="caso-1---regressão-linear-simples"><span class="header-section-number">3.2.1</span> Caso 1 - regressão linear simples</h3>
<p>Um exemplo de regressão linear simples já foi proposto no primeiro capítulo do livro.</p>
</section>
<section id="regressão-linear-múltipla-1" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="regressão-linear-múltipla-1"><span class="header-section-number">3.2.2</span> Regressão linear múltipla</h3>
<p>Carregando pacote para dados e gráfico.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caTools)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A <span class="quarto-unresolved-ref">?fig-dataecn</span> expõe algumas das observações dados macroeconômicos para regressão linear múltipla.</p>
<div id="tbl-dataecn" class="cell anchored" data-tbl-caption="Dados macroeconômicos para o exemplo de regressão múltipla">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(longley)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ?longley</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># dim(longley)</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(longley) <span class="sc">|&gt;</span> <span class="fu">kable</span>()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 17%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 6%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">GNP.deflator</th>
<th style="text-align: right;">GNP</th>
<th style="text-align: right;">Unemployed</th>
<th style="text-align: right;">Armed.Forces</th>
<th style="text-align: right;">Population</th>
<th style="text-align: right;">Year</th>
<th style="text-align: right;">Employed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1947</td>
<td style="text-align: right;">83.0</td>
<td style="text-align: right;">234.289</td>
<td style="text-align: right;">235.6</td>
<td style="text-align: right;">159.0</td>
<td style="text-align: right;">107.608</td>
<td style="text-align: right;">1947</td>
<td style="text-align: right;">60.323</td>
</tr>
<tr class="even">
<td style="text-align: left;">1948</td>
<td style="text-align: right;">88.5</td>
<td style="text-align: right;">259.426</td>
<td style="text-align: right;">232.5</td>
<td style="text-align: right;">145.6</td>
<td style="text-align: right;">108.632</td>
<td style="text-align: right;">1948</td>
<td style="text-align: right;">61.122</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1949</td>
<td style="text-align: right;">88.2</td>
<td style="text-align: right;">258.054</td>
<td style="text-align: right;">368.2</td>
<td style="text-align: right;">161.6</td>
<td style="text-align: right;">109.773</td>
<td style="text-align: right;">1949</td>
<td style="text-align: right;">60.171</td>
</tr>
<tr class="even">
<td style="text-align: left;">1950</td>
<td style="text-align: right;">89.5</td>
<td style="text-align: right;">284.599</td>
<td style="text-align: right;">335.1</td>
<td style="text-align: right;">165.0</td>
<td style="text-align: right;">110.929</td>
<td style="text-align: right;">1950</td>
<td style="text-align: right;">61.187</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1951</td>
<td style="text-align: right;">96.2</td>
<td style="text-align: right;">328.975</td>
<td style="text-align: right;">209.9</td>
<td style="text-align: right;">309.9</td>
<td style="text-align: right;">112.075</td>
<td style="text-align: right;">1951</td>
<td style="text-align: right;">63.221</td>
</tr>
<tr class="even">
<td style="text-align: left;">1952</td>
<td style="text-align: right;">98.1</td>
<td style="text-align: right;">346.999</td>
<td style="text-align: right;">193.2</td>
<td style="text-align: right;">359.4</td>
<td style="text-align: right;">113.270</td>
<td style="text-align: right;">1952</td>
<td style="text-align: right;">63.639</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Na <a href="#fig-corecn" class="quarto-xref">Figura&nbsp;<span>3.10</span></a> visualiza-se a correlação entre as variáveis presentes no conjunto de dados.</p>
<div class="cell" data-fig-caption="Correlação entre variáveis macroeconômicas">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(longley) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-corecn" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-corecn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="AS_reg_ols_files/figure-html/fig-corecn-1.png" id="fig-corecn" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-corecn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.10
</figcaption>
</figure>
</div>
</div>
</div>
<p>Padronizando os dados para evitar efeitos de escala e unidades de medida.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>longley_scaled <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">scale</span>(longley))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Seprando dados de treino e teste.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">45</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>tr <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fl">0.8</span><span class="sc">*</span><span class="fu">nrow</span>(longley_scaled),<span class="dv">0</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>treino <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(longley_scaled), tr, <span class="at">replace =</span> F)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>longley.tr <span class="ot">&lt;-</span> longley_scaled[treino,]</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>longley.te <span class="ot">&lt;-</span> longley_scaled[<span class="sc">-</span>treino,]</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Regressão múltipla para o número de pessoas empregadas em função das outras variáveis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>lm_mult <span class="ot">&lt;-</span> <span class="fu">lm</span>(Employed <span class="sc">~</span>., longley.tr)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_mult)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Employed ~ ., data = longley.tr)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.116622 -0.033371  0.002484  0.031364  0.121138 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  -0.006058   0.025665  -0.236  0.82123   
GNP.deflator  0.154006   0.487336   0.316  0.76269   
GNP          -1.252420   1.218841  -1.028  0.34379   
Unemployed   -0.594009   0.165152  -3.597  0.01141 * 
Armed.Forces -0.233556   0.061149  -3.819  0.00877 **
Population   -0.092484   0.677281  -0.137  0.89585   
Year          2.629894   0.676141   3.890  0.00808 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.09174 on 6 degrees of freedom
Multiple R-squared:  0.9959,    Adjusted R-squared:  0.9917 
F-statistic: 241.1 on 6 and 6 DF,  p-value: 7.003e-07</code></pre>
</div>
</div>
<p>Obtendo os coeficientes com as equações normais de mínimos quadrados passo a passo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span>., <span class="at">data =</span>longley.tr[,<span class="sc">-</span><span class="dv">7</span>])</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>X</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     (Intercept) GNP.deflator        GNP Unemployed Armed.Forces Population
1951           1   -0.5079204 -0.5908091 -1.1710587   0.70742726 -0.7689652
1957           1    0.6225934  0.5540580 -0.2753583   0.27490604  0.4342950
1960           1    1.1600508  1.1560203  0.7894229  -0.13318708  1.1420190
1953           1   -0.2484582 -0.2244927 -1.4161189   1.35117978 -0.3349577
1956           1    0.2704662  0.3167321 -0.3973534   0.35968594  0.1883239
1949           1   -1.2492409 -1.3043364  0.5229601  -1.42356602 -1.0998977
1959           1    1.0117867  0.9558390  0.6631474  -0.07858307  0.8542141
1952           1   -0.3318568 -0.4094719 -1.3497707   1.41871632 -0.5971736
1950           1   -1.1287763 -1.0372705  0.1687464  -1.37470980 -0.9337126
1954           1   -0.1557931 -0.2473611  0.4116664   1.06810111 -0.1732292
1958           1    0.8449896  0.5719362  1.5920219   0.04355747  0.6506518
1947           1   -1.7310992 -1.5434331 -0.8960348  -1.46092666 -1.4111352
1962           1    1.4102465  1.6821336  0.8707530   0.31657752  1.8195537
           Year
1951 -0.7351470
1957  0.5251050
1960  1.1552311
1953 -0.3150630
1956  0.3150630
1949 -1.1552311
1959  0.9451891
1952 -0.5251050
1950 -0.9451891
1954 -0.1050210
1958  0.7351470
1947 -1.5753151
1962  1.5753151
attr(,"assign")
[1] 0 1 2 3 4 5 6</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> longley.tr<span class="sc">$</span>Employed</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>beta_mat <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(X)<span class="sc">%*%</span>X)<span class="sc">%*%</span><span class="fu">t</span>(X)<span class="sc">%*%</span>y</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>beta_mat</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     [,1]
(Intercept)  -0.006058494
GNP.deflator  0.154006386
GNP          -1.252419887
Unemployed   -0.594008870
Armed.Forces -0.233556488
Population   -0.092484035
Year          2.629893534</code></pre>
</div>
</div>
<p>Existem algoritmos de seleção de variáveis que permitem a melhora do ajuste do modelo considerando a remoção de coeficientes não significativos. Um deles é a eliminação para trás. O critério de informação de Akaike, o qual leva em conta o erro dos modelos e a complexidade, é usado para selecionar os modelos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>lm_mult_red <span class="ot">&lt;-</span> <span class="fu">step</span>(lm_mult, <span class="at">direction =</span> <span class="st">"back"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-58.16
Employed ~ GNP.deflator + GNP + Unemployed + Armed.Forces + Population + 
    Year

               Df Sum of Sq      RSS     AIC
- Population    1  0.000157 0.050653 -60.120
- GNP.deflator  1  0.000840 0.051337 -59.946
&lt;none&gt;                      0.050496 -58.160
- GNP           1  0.008886 0.059382 -58.053
- Unemployed    1  0.108874 0.159370 -45.219
- Armed.Forces  1  0.122775 0.173271 -44.132
- Year          1  0.127324 0.177820 -43.795

Step:  AIC=-60.12
Employed ~ GNP.deflator + GNP + Unemployed + Armed.Forces + Year

               Df Sum of Sq     RSS     AIC
- GNP.deflator  1   0.00533 0.05598 -60.820
&lt;none&gt;                      0.05065 -60.120
- GNP           1   0.04735 0.09801 -53.540
- Year          1   0.13005 0.18070 -45.586
- Armed.Forces  1   0.16981 0.22046 -43.001
- Unemployed    1   0.32078 0.37143 -36.219

Step:  AIC=-60.82
Employed ~ GNP + Unemployed + Armed.Forces + Year

               Df Sum of Sq     RSS     AIC
&lt;none&gt;                      0.05598 -60.820
- GNP           1  0.044043 0.10002 -55.275
- Year          1  0.154642 0.21062 -45.594
- Armed.Forces  1  0.188671 0.24465 -43.647
- Unemployed    1  0.315797 0.37178 -38.207</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_mult_red)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Employed ~ GNP + Unemployed + Armed.Forces + Year, 
    data = longley.tr)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.124653 -0.039041 -0.002178  0.039448  0.114711 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -0.006174   0.023368  -0.264  0.79830    
GNP          -1.336743   0.532824  -2.509  0.03644 *  
Unemployed   -0.604450   0.089976  -6.718  0.00015 ***
Armed.Forces -0.216546   0.041703  -5.193  0.00083 ***
Year          2.779766   0.591313   4.701  0.00154 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.08365 on 8 degrees of freedom
Multiple R-squared:  0.9954,    Adjusted R-squared:  0.9931 
F-statistic: 434.8 on 4 and 8 DF,  p-value: 2.19e-09</code></pre>
</div>
</div>
<p>Avaliando o modelo considerando os dados de treino.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>metrics <span class="ot">&lt;-</span> <span class="cf">function</span>(obs, pred) {</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  RSE <span class="ot">&lt;-</span> <span class="fu">sum</span>((obs <span class="sc">-</span> pred)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  SST <span class="ot">&lt;-</span> <span class="fu">sum</span>((obs <span class="sc">-</span> <span class="fu">mean</span>(obs))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  R2 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> RSE<span class="sc">/</span>SST </span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  MAE <span class="ot">&lt;-</span>  <span class="fu">mean</span>(<span class="fu">abs</span>(obs <span class="sc">-</span> pred))</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  RMSE <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((obs <span class="sc">-</span> pred)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">RMSE =</span> RMSE,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>               <span class="at">MAE =</span> MAE,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>               <span class="at">R2 =</span> R2))</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">metrics</span>(longley.tr<span class="sc">$</span>Employed, lm_mult_red<span class="sc">$</span>fitted.values)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        RMSE        MAE        R2
1 0.06562145 0.05009978 0.9954209</code></pre>
</div>
</div>
<p>Avaliando os resíduos do modelo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(lm_mult_red<span class="sc">$</span>residuals)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  lm_mult_red$residuals
W = 0.96685, p-value = 0.854</code></pre>
</div>
</div>
<p>A <a href="#fig-resecn" class="quarto-xref">Figura&nbsp;<span>3.11</span></a> expõe os gráficos de resíduos do modelo.</p>
<div class="cell" data-fig-caption="Gráficos de resíduos  macroeconômicas">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm_mult_red)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-resecn" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-resecn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="AS_reg_ols_files/figure-html/fig-resecn-1.png" id="fig-resecn" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-resecn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.11
</figcaption>
</figure>
</div>
</div>
</div>
<p>Avaliando o modelo com dados de teste.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>pred_mult.te <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_mult_red, <span class="at">newdata=</span>longley.te)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">metrics</span>(longley.te<span class="sc">$</span>Employed, pred_mult.te)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        RMSE        MAE        R2
1 0.08438488 0.06111778 0.9922761</code></pre>
</div>
</div>
</section>
<section id="regressão-múltipla-com-variáveis-categóricas" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="regressão-múltipla-com-variáveis-categóricas"><span class="header-section-number">3.2.3</span> Regressão múltipla com variáveis categóricas</h3>
<p>Pacote para dados e para codificação de variáveis dummy ou dicotômicas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastDummies)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Carregando conjunto de dados com variáveis contínuas e uma categórica.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Grunfeld)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ?Grunfeld</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Grunfeld)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  invest  value capital           firm year
1  317.6 3078.5     2.8 General Motors 1935
2  391.8 4661.7    52.6 General Motors 1936
3  410.6 5387.1   156.9 General Motors 1937
4  257.7 2792.2   209.2 General Motors 1938
5  330.8 4313.2   203.4 General Motors 1939
6  461.2 4643.9   207.2 General Motors 1940</code></pre>
</div>
</div>
<p>A <a href="#fig-corfirms" class="quarto-xref">Figura&nbsp;<span>3.12</span></a> expõe gráficos de densidade, correlação aos pares e coeficientes de correlação de Pearson para cada nível da variável categórica <code>firm</code> (firma). Foram consideradas apenas três empresas para não dificultar a interpretação. Consegue fazer para as outras empresas?</p>
<div class="cell" data-fig-caption="Matriz de gráficos generalizados aos pares do conjunto de dados `Grunfeld`, para avaliar distribuição e correlação">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(Grunfeld[<span class="dv">1</span><span class="sc">:</span><span class="dv">60</span>,], <span class="at">columns =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="fu">aes</span>(<span class="at">color =</span> firm, <span class="at">alpha =</span> <span class="fl">0.5</span>)) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-corfirms" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-corfirms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="AS_reg_ols_files/figure-html/fig-corfirms-1.png" id="fig-corfirms" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-corfirms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.12
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(Grunfeld<span class="sc">$</span>firm)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "General Motors"    "US Steel"          "General Electric" 
 [4] "Chrysler"          "Atlantic Refining" "IBM"              
 [7] "Union Oil"         "Westinghouse"      "Goodyear"         
[10] "Diamond Match"     "American Steel"   </code></pre>
</div>
</div>
<p>Codificando a variável <code>firm</code> em variáveis binárias.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>Grunfeld2 <span class="ot">&lt;-</span> <span class="fu">dummy_cols</span>(Grunfeld, <span class="at">select_columns =</span> <span class="fu">c</span>(<span class="st">"firm"</span>))</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>Grunfeld2 <span class="ot">&lt;-</span> Grunfeld2[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">16</span>)] <span class="co"># removendo coluna da variável "firm" e coluna da última variável binária criada, a qual é desnecessária</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Grunfeld)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  invest  value capital           firm year
1  317.6 3078.5     2.8 General Motors 1935
2  391.8 4661.7    52.6 General Motors 1936
3  410.6 5387.1   156.9 General Motors 1937
4  257.7 2792.2   209.2 General Motors 1938
5  330.8 4313.2   203.4 General Motors 1939
6  461.2 4643.9   207.2 General Motors 1940</code></pre>
</div>
</div>
<p>Padronizando variáveis regressoras contínuas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>Grunfeld2[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="fu">scale</span>(Grunfeld2[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>])</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dividindo dados de treino e teste.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">87</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>tr <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fl">0.8</span><span class="sc">*</span><span class="fu">nrow</span>(Grunfeld2),<span class="dv">0</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>treino <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(Grunfeld2), tr, <span class="at">replace =</span> F)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>Grunfeld.tr <span class="ot">&lt;-</span> Grunfeld2[treino,]</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>Grunfeld.te <span class="ot">&lt;-</span> Grunfeld2[<span class="sc">-</span>treino,]</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Modelo de regressão linear múltipla com variáveis contínuas e categóricas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>lm_invest <span class="ot">&lt;-</span> <span class="fu">lm</span>(invest <span class="sc">~</span> .<span class="sc">-</span>year, Grunfeld.tr)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_invest)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = invest ~ . - year, data = Grunfeld.tr)

Residuals:
     Min       1Q   Median       3Q      Max 
-177.977  -12.831   -0.035   13.412  197.819 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               158.512     14.627  10.837  &lt; 2e-16 ***
value                     141.105     14.368   9.821  &lt; 2e-16 ***
capital                    76.787      5.533  13.877  &lt; 2e-16 ***
`firm_General Motors`     -25.829     47.263  -0.546  0.58547    
`firm_US Steel`           125.052     26.010   4.808 3.44e-06 ***
`firm_General Electric`  -202.654     25.570  -7.926 3.38e-13 ***
firm_Chrysler              -7.712     17.307  -0.446  0.65646    
`firm_Atlantic Refining`  -76.358     17.943  -4.256 3.51e-05 ***
firm_IBM                   -3.460     16.713  -0.207  0.83625    
`firm_Union Oil`          -29.516     16.107  -1.833  0.06869 .  
firm_Westinghouse         -34.198     17.161  -1.993  0.04795 *  
firm_Goodyear             -56.218     17.078  -3.292  0.00122 ** 
`firm_Diamond Match`       10.857     15.651   0.694  0.48883    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 46.73 on 163 degrees of freedom
Multiple R-squared:  0.9443,    Adjusted R-squared:  0.9402 
F-statistic: 230.5 on 12 and 163 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Outra forma de inclusão de variáveis dummy em modelos de regressão múltipla é na interação. A diferença é que no caso anterior as variáveis dummy mudam apenas a constante, enquanto neste caso, vão mudar a inclinação.</p>
<p>Supondo o caso da empresa General Electric que no gráfico <em>pairs</em> aparenta ter inclinação distinta das demais.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>lm_invest2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(invest <span class="sc">~</span> . <span class="sc">+</span> <span class="fu">I</span>(capital<span class="sc">*</span><span class="st">`</span><span class="at">firm_General Electric</span><span class="st">`</span>), Grunfeld.tr)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_invest2)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = invest ~ . + I(capital * `firm_General Electric`), 
    data = Grunfeld.tr)

Residuals:
    Min      1Q  Median      3Q     Max 
-179.22  -12.00    1.06   12.39  184.42 

Coefficients:
                                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                           163.389     14.679  11.131  &lt; 2e-16 ***
value                                 137.675     14.076   9.781  &lt; 2e-16 ***
capital                                87.834      7.203  12.194  &lt; 2e-16 ***
year                                   -4.245      4.641  -0.915 0.361718    
`firm_General Motors`                 -34.125     47.124  -0.724 0.470018    
`firm_US Steel`                       121.936     25.838   4.719 5.11e-06 ***
`firm_General Electric`              -193.220     26.307  -7.345 9.71e-12 ***
firm_Chrysler                          -8.519     16.928  -0.503 0.615497    
`firm_Atlantic Refining`              -92.113     18.817  -4.895 2.37e-06 ***
firm_IBM                               -3.521     16.284  -0.216 0.829092    
`firm_Union Oil`                      -38.768     16.397  -2.364 0.019253 *  
firm_Westinghouse                     -33.498     16.749  -2.000 0.047185 *  
firm_Goodyear                         -64.341     17.112  -3.760 0.000237 ***
`firm_Diamond Match`                   12.949     15.266   0.848 0.397568    
I(capital * `firm_General Electric`)  -44.741     14.660  -3.052 0.002662 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 45.53 on 161 degrees of freedom
Multiple R-squared:  0.9478,    Adjusted R-squared:  0.9433 
F-statistic: 208.9 on 14 and 161 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>A <a href="#fig-betafirms" class="quarto-xref">Figura&nbsp;<span>3.13</span></a> a seguir ilustra a mudança da inclinação para a empresa GE em relação a outras três selecionadas arbitrariamente. Em um caso com tantos níveis de variáveis dummy como este é difícil explorar todas possibilidades. Uma sugestão seria fazer um modelo com todas interações possíveis e posteriormente usar a função step para realizar eliminação para trás (<em>backward elimination</em>) para remover os termos não significativos.</p>
<div class="cell" data-fig-caption="Mudança da inclinação para a empresa GE em relação a outras três selecionadas arbitrariamente">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>Grunfeld_select <span class="ot">&lt;-</span> Grunfeld <span class="sc">|&gt;</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(firm <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"General Motors"</span>,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"US Steel"</span>,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"General Electric"</span>,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"IBM"</span>))</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Grunfeld_select, <span class="fu">aes</span>(<span class="at">x=</span>capital,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">y=</span>invest)) <span class="sc">+</span> </span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">color =</span> firm, <span class="at">size=</span>value), <span class="at">alpha =</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">col=</span>firm), <span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span>F) <span class="sc">+</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>g</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-betafirms" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-betafirms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="AS_reg_ols_files/figure-html/fig-betafirms-1.png" id="fig-betafirms" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-betafirms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.13
</figcaption>
</figure>
</div>
</div>
</div>
<p>Avaliando o modelo considerando os dados de treino.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">metrics</span>(Grunfeld.tr<span class="sc">$</span>invest, lm_invest<span class="sc">$</span>fitted.values)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      RMSE      MAE        R2
1 44.97067 25.96427 0.9443401</code></pre>
</div>
</div>
<p>Avaliando o modelo considerando os dados de teste.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>pred.invest <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_invest, <span class="at">newdata =</span> Grunfeld.te)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">metrics</span>(Grunfeld.te<span class="sc">$</span>invest, pred.invest)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      RMSE      MAE        R2
1 66.90304 36.76732 0.9391516</code></pre>
</div>
</div>
<p>Adicionando termo de interaçao ao modelo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>lm_invest_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(invest <span class="sc">~</span> . <span class="sc">+</span> value<span class="sc">*</span>capital, Grunfeld.tr)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_invest_int)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = invest ~ . + value * capital, data = Grunfeld.tr)

Residuals:
     Min       1Q   Median       3Q      Max 
-146.016  -11.418   -2.304   12.401  192.342 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               66.0183    16.3423   4.040 8.27e-05 ***
value                    102.4319    12.5440   8.166 8.77e-14 ***
capital                   -0.3027    10.8409  -0.028 0.977757    
year                      21.3233     4.8910   4.360 2.31e-05 ***
`firm_General Motors`    157.6237    45.0929   3.496 0.000611 ***
`firm_US Steel`          249.4813    26.0617   9.573  &lt; 2e-16 ***
`firm_General Electric`  -58.0340    27.4135  -2.117 0.035797 *  
firm_Chrysler             39.1575    15.1944   2.577 0.010861 *  
`firm_Atlantic Refining`  69.6205    23.1453   3.008 0.003053 ** 
firm_IBM                  25.2365    14.0326   1.798 0.073983 .  
`firm_Union Oil`          53.0164    16.8449   3.147 0.001964 ** 
firm_Westinghouse         -2.1632    14.5174  -0.149 0.881735    
firm_Goodyear             29.0504    17.4580   1.664 0.098054 .  
`firm_Diamond Match`      -7.8207    12.9832  -0.602 0.547777    
value:capital             29.3232     3.2597   8.996 6.22e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 38.2 on 161 degrees of freedom
Multiple R-squared:  0.9633,    Adjusted R-squared:  0.9601 
F-statistic: 301.5 on 14 and 161 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Consegue fazer os próximos passos para avaliar o modelo com interação nos dados de teste?</p>
</section>
<section id="regressão-polinomial-1" class="level3" data-number="3.2.4">
<h3 data-number="3.2.4" class="anchored" data-anchor-id="regressão-polinomial-1"><span class="header-section-number">3.2.4</span> Regressão polinomial</h3>
<p>Carregando pacote e dados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>rehab <span class="ot">&lt;-</span> wtloss</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ?wtloss</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Visualizando o comportamento do peso (massa) em função de dias de treinamento.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rehab, <span class="fu">aes</span>(<span class="at">x =</span> Days, <span class="at">y =</span> Weight)) <span class="sc">+</span> </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"deepskyblue3"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Dias"</span>) <span class="sc">+</span> </span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Peso"</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Separando dados de treino e teste.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">53</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>tr <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fl">0.75</span><span class="sc">*</span><span class="fu">nrow</span>(rehab),<span class="dv">0</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>treino <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(rehab), tr, <span class="at">replace =</span> F)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>rehab.tr <span class="ot">&lt;-</span> rehab[treino,]</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>rehab.te <span class="ot">&lt;-</span> rehab[<span class="sc">-</span>treino,]</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Estimando modelos linear e quadrático.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Weight <span class="sc">~</span> Days, rehab.tr)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>lm2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Weight <span class="sc">~</span> Days <span class="sc">+</span> <span class="fu">I</span>(Days<span class="sc">^</span><span class="dv">2</span>), rehab.tr)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm2)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Desempenho para dados de treino.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">metrics</span>(rehab.tr<span class="sc">$</span>Weight, lm1<span class="sc">$</span>fitted.values)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">metrics</span>(rehab.tr<span class="sc">$</span>Weight, lm2<span class="sc">$</span>fitted.values)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Desempenho dos modelos para dados de teste.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>pred.lm1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm1, <span class="at">newdata =</span> rehab.te)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">metrics</span>(rehab.te<span class="sc">$</span>Weight, pred.lm1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>pred.lm2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm2, <span class="at">newdata =</span> rehab.te)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">metrics</span>(rehab.te<span class="sc">$</span>Weight, pred.lm2)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Plotando o modelo com dados de teste.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> rehab.tr, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Days, <span class="at">y =</span> Weight), <span class="at">color =</span> <span class="st">"deepskyblue3"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> rehab.te, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Days, <span class="at">y =</span> Weight), </span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x <span class="sc">+</span> <span class="fu">I</span>(x<span class="sc">^</span><span class="dv">2</span>), <span class="at">se =</span> F, <span class="at">col =</span> <span class="st">"mediumvioletred"</span>) <span class="sc">+</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Peso vs Dias (dados de teste)"</span>) <span class="sc">+</span> </span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Dias"</span>) <span class="sc">+</span> </span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Peso"</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="referências" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="referências">Referências</h2>
<p>Hastie, T., Tibshirani, R., Friedman, J. H., &amp; Friedman, J. H. (2009). The elements of statistical learning: data mining, inference, and prediction (Vol. 2, pp.&nbsp;1-758). New York: springer.</p>
<p>Gareth, J., Daniela, W., Trevor, H., &amp; Robert, T. (2013). An introduction to statistical learning: with applications in R. Spinger.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./AS_vicio_var.html" class="pagination-link" aria-label="Conflito entre vício e variância no Aprendizado supervisionado">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Conflito entre vício e variância no Aprendizado supervisionado</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>